#!/usr/bin/env python3
import sys
import argparse
import requests

workspace = 'iic215420132'
url = 'https://' + workspace + '.kanbanery.com/api/v1'
headers = ''
project = '39793'

def search_task(owner_id):
	print('hi')


def get_users():
	r = requests.get(url + '/projects/' + project + '/users.json', headers=headers)
	params = r.json()
	for user in params:
		print(user['name'])
	#print('Welcome, ' + params['name'])

def get_user_info():
	r = requests.get(url + '/user.json', headers=headers)
	params = r.json()
	print('Welcome, ' + params['name'])

def main():

	parser = argparse.ArgumentParser(description='Python front end for kanbanery')
	parser.add_argument('-u', '--user', action='store_true')
	parser.add_argument('-a', '--all', action='store_true')
	parser.add_argument('-t', '--token', required=True)

	args = parser.parse_args()
	global headers
	headers = {'X-Kanbanery-ApiToken' : args.token }

	if args.user:
		get_user_info()
	if args.all:
		get_users()

	return 0


if __name__ == "__main__":
   sys.exit(main())